services:
  gateway:
    container_name: gateway
    image: nginx:latest
    networks:
      - authentication
    ports:
      - 80:80
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - authentication
  
  authentication:
    build:
      context: ./authentication
      dockerfile: Dockerfile
    deploy:
      replicas: 2
    networks:
      - authentication

networks:
  authentication: