services:
  gateway:
    container_name: website_rework_gateway
    image: nginx:latest
    networks:
      - authentication
      - agenda
      - job
    ports:
      - 80:80
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - authentication
      - agenda
      - job

  authentication:
    build:
      context: ./authentication
      dockerfile: Dockerfile
    deploy:
      replicas: ${REPLICAS}
    networks:
      - authentication
    depends_on:
      - db-authentication

  agenda:
    build:
      context: ./agenda
      dockerfile: Dockerfile
    deploy:
      replicas: ${REPLICAS}
    networks:
      - agenda

  job:
    build:
      context: ./job
      dockerfile: Dockerfile
    deploy:
      replicas: ${REPLICAS}
    networks:
      - job

  db-authentication:
    container_name: website_rework_authentication_db
    image: mongo:latest
    networks:
      - authentication
    volumes:
      - ./authentication/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}

networks:
  authentication:
  agenda:
  job:
