services:
  gateway:
    container_name: gateway
    image: nginx:latest
    networks:
      - authentication
      - agenda
      - job
    ports:
      - 80:80
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - authentication
      - agenda
      - job

  authentication:
    build:
      context: ./authentication
      dockerfile: Dockerfile
    deploy:
      replicas: ${REPLICAS}
    networks:
      - authentication

  agenda:
    build:
      context: ./agenda
      dockerfile: Dockerfile
    deploy:
      replicas: ${REPLICAS}
    networks:
      - agenda

  job:
    build:
      context: ./job
      dockerfile: Dockerfile
    deploy:
      replicas: ${REPLICAS}
    networks:
      - job

networks:
  authentication:
  agenda:
  job:
